### ISSUE TITLE
Artst and Album on Android Auto gives an error

### ISSUE THREAD

**Issue by ryandikdan** [puff/finamp#1]
Thank you so much for all your work on the Android auto version of finamp!! It works quite well. I can change the song in the app, then hook up to the car and it plays where I left off and looks and feels great. I have one issue, which I have a suggestion for, and then I have a couple of requests.

When I go to Artist or Album, I think that I have too many (not sure how many is too many possibly >1000), and it loads for a couple of minutes, then gives an error. I imagine that it's trying to list every one of my artists/albums it's too many. Perhaps you could have it simply load the most recently played 100 for each? Or perhaps the most recently added or something? Anything would be better than it just not being able to show anything.

Now my requests are a bit much, especially after you've done such great work already! But I will ask anyway. 

1. Would it be possible to put a favorite button on the now playing screen so I can know if they've been favorited and I can favorite them?
2. Could there be some rudimentary search function for artists and albums? That way I could access anything despite it not being able to load.

Thanks again for everything you've done!

**Comment by puff** [comment]
Hi, I know this is super late but I've been working on getting this merged into upstream. It *should* be out with the next beta redesign release and be much more stable than this fork.

There is a hard limit of 100 items in it currently, but pagination will likely be added later. Same with favorites and other options.
